version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: trackwise-postgres
    restart: always
    environment:
      POSTGRES_USER: trackwise_user
      POSTGRES_PASSWORD: trackwise_pass
      POSTGRES_DB: trackwise_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trackwise-net

  ticket-service:
    build:
      context: .
      dockerfile: ticket-service/Dockerfile
    container_name: trackwise-ticket
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trackwise_db
      SPRING_DATASOURCE_USERNAME: trackwise_user
      SPRING_DATASOURCE_PASSWORD: trackwise_pass
    depends_on:
      - postgres
    networks:
      - trackwise-net

volumes:
  postgres_data:

networks:
  trackwise-net:
